version: '3.9'
services:
    webscraper:
        container_name: webscraper
        image: webscraper:latest
        build: .
        command: watchmedo auto-restart --recursive --patterns *.py --directory . --directory /pythontools -- python app.py'
        volumes:
            - .:/app