version: '3.9'
services:
    webscraper:
        container_name: webscraper
        image: webscraper:latest
        build: .
        volumes:
            - ./src:/app
            - ./pythontools:/pythontools